In [28]:
# importing pandas
import pandas as pd
  
# merging two csv files
df = pd.concat(
    map(pd.read_csv, ['2019.csv', '2020.csv', '2021.csv']), ignore_index=True)

In [29]:
df.head(5)

,Unnamed: 0,Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,...,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost,Year,Year
0,0.0,Christian McCaffrey,CAR,RB,23,16,16,142.0,116.0,0.0,...,15.0,287.0,1005.0,4.0,469.20,0.0,1.0,0.0,2019.0,NaN
1,1.0,Lamar Jackson,BAL,QB,22,15,15,0.0,0.0,3127.0,...,7.0,176.0,0.0,0.0,415.68,6.0,9.0,2.0,2019.0,NaN
2,2.0,Derrick Henry,TEN,RB,25,15,15,24.0,18.0,0.0,...,16.0,303.0,206.0,2.0,294.60,0.0,5.0,3.0,2019.0,NaN
3,3.0,Aaron Jones,GNB,RB,25,16,16,68.0,49.0,0.0,...,16.0,236.0,474.0,3.0,314.80,0.0,3.0,2.0,2019.0,NaN
4,4.0,Ezekiel Elliott,DAL,RB,24,16,16,71.0,54.0,0.0,...,12.0,301.0,420.0,2.0,311.70,0.0,3.0,2.0,2019.0,NaN

In [30]:
# Shape is just an attribute that tells us the shape of our DataFrame in the format (rows, columns)
print(df.shape) 
print('We have', df.shape[0], 'players we can analyze for the 2021 season')
print('We have', df.shape[1], 'columns of data we can analyze for the 2021 season')

(1917, 23)
We have 1917 players we can analyze for the 2021 season
We have 23 columns of data we can analyze for the 2021 season

In [31]:
# Displaying columns
df.columns

Index(['Unnamed: 0', 'Player', 'Tm', 'Pos', 'Age', 'G', 'GS', 'Tgt', 'Rec',
       'PassingYds', 'PassingTD', 'PassingAtt', 'RushingYds', 'RushingTD',
       'RushingAtt', 'ReceivingYds', 'ReceivingTD', 'FantasyPoints', 'Int',
       'Fumbles', 'FumblesLost', 'Year ', 'Year'],
      dtype='object')

In [32]:
# 2022 NFL RB Draft Order Data Frame 
main_df = df[['Player', 'Tm', 'Pos', 'Tgt', 'Rec', 'GS', 'ReceivingYds', 'RushingYds', 'RushingTD', 'RushingAtt', 'ReceivingTD', 'FantasyPoints', 'Year']]
main_df.head(10)

,Player,Tm,Pos,Tgt,Rec,GS,ReceivingYds,RushingYds,RushingTD,RushingAtt,ReceivingTD,FantasyPoints,Year
0,Christian McCaffrey,CAR,RB,142.0,116.0,16,1005.0,1387.0,15.0,287.0,4.0,469.20,NaN
1,Lamar Jackson,BAL,QB,0.0,0.0,15,0.0,1206.0,7.0,176.0,0.0,415.68,NaN
2,Derrick Henry,TEN,RB,24.0,18.0,15,206.0,1540.0,16.0,303.0,2.0,294.60,NaN
3,Aaron Jones,GNB,RB,68.0,49.0,16,474.0,1084.0,16.0,236.0,3.0,314.80,NaN
4,Ezekiel Elliott,DAL,RB,71.0,54.0,16,420.0,1357.0,12.0,301.0,2.0,311.70,NaN
5,Dalvin Cook,MIN,RB,63.0,53.0,14,519.0,1135.0,13.0,250.0,0.0,292.40,NaN
6,Michael Thomas,NOR,WR,185.0,149.0,15,1725.0,-9.0,0.0,1.0,9.0,374.60,NaN
7,Travis Kelce,KAN,TE,136.0,97.0,16,1229.0,4.0,1.0,1.0,5.0,254.30,NaN
8,Nick Chubb,CLE,RB,49.0,36.0,16,278.0,1494.0,8.0,298.0,0.0,255.20,NaN
9,Austin Ekeler,LAC,RB,108.0,92.0,8,993.0,557.0,3.0,132.0,8.0,309.00,NaN

In [33]:
# Changing column names from  G to Games (Played) and AVG to (ADP) Average Draft Position and viewing
main_df = main_df.rename(columns={'Tm':'Team', 'GS':'Games'})
main_df.head(10)

,Player,Team,Pos,Tgt,Rec,Games,ReceivingYds,RushingYds,RushingTD,RushingAtt,ReceivingTD,FantasyPoints,Year
0,Christian McCaffrey,CAR,RB,142.0,116.0,16,1005.0,1387.0,15.0,287.0,4.0,469.20,NaN
1,Lamar Jackson,BAL,QB,0.0,0.0,15,0.0,1206.0,7.0,176.0,0.0,415.68,NaN
2,Derrick Henry,TEN,RB,24.0,18.0,15,206.0,1540.0,16.0,303.0,2.0,294.60,NaN
3,Aaron Jones,GNB,RB,68.0,49.0,16,474.0,1084.0,16.0,236.0,3.0,314.80,NaN
4,Ezekiel Elliott,DAL,RB,71.0,54.0,16,420.0,1357.0,12.0,301.0,2.0,311.70,NaN
5,Dalvin Cook,MIN,RB,63.0,53.0,14,519.0,1135.0,13.0,250.0,0.0,292.40,NaN
6,Michael Thomas,NOR,WR,185.0,149.0,15,1725.0,-9.0,0.0,1.0,9.0,374.60,NaN
7,Travis Kelce,KAN,TE,136.0,97.0,16,1229.0,4.0,1.0,1.0,5.0,254.30,NaN
8,Nick Chubb,CLE,RB,49.0,36.0,16,278.0,1494.0,8.0,298.0,0.0,255.20,NaN
9,Austin Ekeler,LAC,RB,108.0,92.0,8,993.0,557.0,3.0,132.0,8.0,309.00,NaN

In [34]:
# Running Back Featured Columns with Usage Ranking and Total Yards From Scrimmage
skill_df = main_df.loc[df['Pos'] == 'RB', ['Player', 'Team', 'Pos','Tgt', 'Rec','RushingAtt', 'ReceivingYds','FantasyPoints', 'Games',]]
skill_df['Usage'] = ((df['Tgt'] + df['RushingAtt']) / main_df['Games'])
skill_df['Touchdowns'] = df['RushingTD'] + df['ReceivingTD']
skill_df['TotYdsScrm']= df['ReceivingYds']+ df['RushingYds']
skill_df.head(100)

,Player,Team,Pos,Tgt,Rec,RushingAtt,ReceivingYds,FantasyPoints,Games,Usage,Touchdowns,TotYdsScrm
0,Christian McCaffrey,CAR,RB,142.0,116.0,287.0,1005.0,469.20,16,26.812500,19.0,2392.0
2,Derrick Henry,TEN,RB,24.0,18.0,303.0,206.0,294.60,15,21.800000,18.0,1746.0
3,Aaron Jones,GNB,RB,68.0,49.0,236.0,474.0,314.80,16,19.000000,19.0,1558.0
4,Ezekiel Elliott,DAL,RB,71.0,54.0,301.0,420.0,311.70,16,23.250000,14.0,1777.0
5,Dalvin Cook,MIN,RB,63.0,53.0,250.0,519.0,292.40,14,22.357143,13.0,1654.0
...,...,...,...,...,...,...,...,...,...,...,...,...
352,T.J. Yeldon,BUF,RB,15.0,13.0,17.0,124.0,29.70,0,inf,0.0,187.0
353,Andrew Beck,DEN,RB,12.0,9.0,1.0,90.0,24.54,6,2.166667,1.0,93.0
359,Wendell Smallwood,WAS,RB,13.0,9.0,22.0,64.0,23.50,0,inf,0.0,145.0
362,Trey Edmunds,PIT,RB,7.0,6.0,22.0,48.0,20.00,0,inf,0.0,140.0
364,Wes Hills,DET,RB,2.0,2.0,10.0,1.0,16.20,1,12.000000,2.0,22.0