In [1]:
import pandas as pd #import pandas in to our code so we can use it
import plotly.express as px  
import datetime as dt
import time 
data1 = pd.read_csv('data/2021.csv') 
data2 = pd.read_csv('data/2020.csv') 

df = pd.merge(data1, data2, 
                   on = 'Player',
                   how ='left')
df.tail(10)

,Unnamed: 0,Player,Tm_x,Pos_x,Age_x,G_x,GS_x,Tgt_x,Rec_x,PassingYds_x,...,RushingYds_y,RushingTD_y,RushingAtt_y,ReceivingYds_y,ReceivingTD_y,FantasyPoints_y,Int_y,Fumbles_y,FumblesLost_y,Year_y
661,661,Jacob Eason,IND,QB,24,1,0,0.0,0.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,662,Feleipe Franks,ATL,QB,24,9,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,663,Racey McMath,TEN,WR,22,9,0,6.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,664,Malik Taylor,GNB,WR,26,10,0,3.0,2.0,0.0,...,9.0,0.0,1.0,66.0,1.0,14.0,0.0,0.0,0.0,2020.0
665,665,Logan Woodside,TEN,QB,26,5,0,0.0,0.0,0.0,...,10.0,0.0,7.0,0.0,0.0,1.0,0.0,0.0,0.0,2020.0
666,666,Travis Benjamin,SFO,NaN,32,10,0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
667,667,Trenton Cannon,2TM,RB,27,12,0,0.0,0.0,0.0,...,33.0,0.0,10.0,16.0,0.0,5.0,0.0,0.0,0.0,2020.0
668,668,John Wolford,LAR,QB,26,3,0,0.0,0.0,5.0,...,56.0,0.0,6.0,0.0,0.0,13.0,1.0,0.0,0.0,2020.0
669,669,Josh Rosen,ATL,QB,24,4,0,0.0,0.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,670,Diontae Spencer,DEN,WR,29,15,0,4.0,1.0,0.0,...,19.0,0.0,3.0,26.0,0.0,11.0,0.0,2.0,0.0,2020.0

In [2]:
data3 = pd.read_csv('data/2019.csv') 

nfl_df = pd.merge(df, data3, 
                   on = 'Player',
                   how ='outer')
nfl_df.head(10)

,Unnamed: 0_x,Player,Tm_x,Pos_x,Age_x,G_x,GS_x,Tgt_x,Rec_x,PassingYds_x,...,RushingYds,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost,Year
0,0.0,Jonathan Taylor,IND,RB,22.0,17.0,17.0,51.0,40.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,Cooper Kupp,LAR,WR,28.0,17.0,17.0,191.0,145.0,0.0,...,4.0,0.0,2.0,1161.0,10.0,270.50,0.0,3.0,0.0,2019.0
2,2.0,Deebo Samuel,SFO,WR,25.0,16.0,15.0,121.0,77.0,24.0,...,159.0,3.0,14.0,802.0,3.0,187.10,0.0,2.0,1.0,2019.0
3,3.0,Josh Allen,BUF,QB,25.0,17.0,17.0,0.0,0.0,4407.0,...,510.0,9.0,109.0,0.0,0.0,282.56,9.0,14.0,4.0,2019.0
4,4.0,Austin Ekeler,LAC,RB,26.0,16.0,16.0,94.0,70.0,0.0,...,557.0,3.0,132.0,993.0,8.0,309.00,0.0,3.0,2.0,2019.0
5,5.0,Justin Herbert,LAC,QB,23.0,17.0,17.0,0.0,0.0,5014.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6.0,Tom Brady,TAM,QB,44.0,17.0,17.0,0.0,0.0,5316.0,...,34.0,3.0,26.0,0.0,0.0,261.68,8.0,4.0,1.0,2019.0
7,7.0,Mark Andrews,BAL,TE,26.0,17.0,9.0,153.0,107.0,0.0,...,0.0,0.0,0.0,852.0,10.0,207.20,0.0,2.0,1.0,2019.0
8,8.0,Ja'Marr Chase,CIN,WR,21.0,17.0,17.0,128.0,81.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9.0,Justin Jefferson,MIN,WR,22.0,17.0,17.0,167.0,108.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
df.head(5)

,Unnamed: 0,Player,Tm_x,Pos_x,Age_x,G_x,GS_x,Tgt_x,Rec_x,PassingYds_x,...,RushingYds_y,RushingTD_y,RushingAtt_y,ReceivingYds_y,ReceivingTD_y,FantasyPoints_y,Int_y,Fumbles_y,FumblesLost_y,Year_y
0,0,Jonathan Taylor,IND,RB,22,17,17,51.0,40.0,0.0,...,1169.0,11.0,232.0,299.0,1.0,217.0,0.0,1.0,1.0,2020.0
1,1,Cooper Kupp,LAR,WR,28,17,17,191.0,145.0,0.0,...,33.0,0.0,4.0,974.0,3.0,117.0,0.0,1.0,1.0,2020.0
2,2,Deebo Samuel,SFO,WR,25,16,15,121.0,77.0,24.0,...,26.0,0.0,8.0,391.0,1.0,48.0,0.0,0.0,0.0,2020.0
3,3,Josh Allen,BUF,QB,25,17,17,0.0,0.0,4407.0,...,421.0,8.0,102.0,12.0,1.0,395.0,10.0,9.0,6.0,2020.0
4,4,Austin Ekeler,LAC,RB,26,16,16,94.0,70.0,0.0,...,530.0,1.0,116.0,403.0,2.0,111.0,0.0,1.0,0.0,2020.0

In [65]:
df.columns

Index(['Unnamed: 0', 'Player', 'Tm_x', 'Pos_x', 'Age_x', 'G_x', 'GS_x',
       'Tgt_x', 'Rec_x', 'PassingYds_x', 'PassingTD_x', 'PassingAtt_x',
       'RushingYds_x', 'RushingTD_x', 'RushingAtt_x', 'ReceivingYds_x',
       'ReceivingTD_x', 'FantasyPoints_x', 'Int_x', 'Fumbles_x',
       'FumblesLost_x', 'Year_x', 'Tm_y', 'Pos_y', 'Age_y', 'G_y', 'GS_y',
       'Tgt_y', 'Rec_y', 'PassingYds_y', 'PassingTD_y', 'PassingAtt_y',
       'RushingYds_y', 'RushingTD_y', 'RushingAtt_y', 'ReceivingYds_y',
       'ReceivingTD_y', 'FantasyPoints_y', 'Int_y', 'Fumbles_y',
       'FumblesLost_y', 'Year_y'],
      dtype='object')

In [66]:
# Shape is just an attribute that tells us the shape of our DataFrame in the format (rows, columns)
print(df.shape) 
print('We have', df.shape[0], 'players we can analyze for all seasons')
print('We have', df.shape[1], 'columns of data we can analyze for all seasons')

(671, 42)
We have 671 players we can analyze for all seasons
We have 42 columns of data we can analyze for all seasons

In [67]:
# Displaying columns
df.columns

Index(['Unnamed: 0', 'Player', 'Tm_x', 'Pos_x', 'Age_x', 'G_x', 'GS_x',
       'Tgt_x', 'Rec_x', 'PassingYds_x', 'PassingTD_x', 'PassingAtt_x',
       'RushingYds_x', 'RushingTD_x', 'RushingAtt_x', 'ReceivingYds_x',
       'ReceivingTD_x', 'FantasyPoints_x', 'Int_x', 'Fumbles_x',
       'FumblesLost_x', 'Year_x', 'Tm_y', 'Pos_y', 'Age_y', 'G_y', 'GS_y',
       'Tgt_y', 'Rec_y', 'PassingYds_y', 'PassingTD_y', 'PassingAtt_y',
       'RushingYds_y', 'RushingTD_y', 'RushingAtt_y', 'ReceivingYds_y',
       'ReceivingTD_y', 'FantasyPoints_y', 'Int_y', 'Fumbles_y',
       'FumblesLost_y', 'Year_y'],
      dtype='object')

In [68]:
# Cleaned RB df dropping na and nan values
skill_df = df.dropna(thresh=2, axis=1)
skill_df.head(10)

,Unnamed: 0,Player,Tm_x,Pos_x,Age_x,G_x,GS_x,Tgt_x,Rec_x,PassingYds_x,...,RushingYds_y,RushingTD_y,RushingAtt_y,ReceivingYds_y,ReceivingTD_y,FantasyPoints_y,Int_y,Fumbles_y,FumblesLost_y,Year_y
0,0,Jonathan Taylor,IND,RB,22,17,17,51.0,40.0,0.0,...,1169.0,11.0,232.0,299.0,1.0,217.0,0.0,1.0,1.0,2020.0
1,1,Cooper Kupp,LAR,WR,28,17,17,191.0,145.0,0.0,...,33.0,0.0,4.0,974.0,3.0,117.0,0.0,1.0,1.0,2020.0
2,2,Deebo Samuel,SFO,WR,25,16,15,121.0,77.0,24.0,...,26.0,0.0,8.0,391.0,1.0,48.0,0.0,0.0,0.0,2020.0
3,3,Josh Allen,BUF,QB,25,17,17,0.0,0.0,4407.0,...,421.0,8.0,102.0,12.0,1.0,395.0,10.0,9.0,6.0,2020.0
4,4,Austin Ekeler,LAC,RB,26,16,16,94.0,70.0,0.0,...,530.0,1.0,116.0,403.0,2.0,111.0,0.0,1.0,0.0,2020.0
5,5,Justin Herbert,LAC,QB,23,17,17,0.0,0.0,5014.0,...,234.0,5.0,55.0,0.0,0.0,333.0,10.0,8.0,1.0,2020.0
6,6,Tom Brady,TAM,QB,44,17,17,0.0,0.0,5316.0,...,6.0,3.0,30.0,0.0,0.0,338.0,12.0,4.0,1.0,2020.0
7,7,Mark Andrews,BAL,TE,26,17,9,153.0,107.0,0.0,...,0.0,0.0,0.0,701.0,7.0,112.0,0.0,2.0,0.0,2020.0
8,8,Ja'Marr Chase,CIN,WR,21,17,17,128.0,81.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Justin Jefferson,MIN,WR,22,17,17,167.0,108.0,35.0,...,2.0,0.0,1.0,1400.0,7.0,186.0,0.0,1.0,0.0,2020.0

In [74]:
import datetime as dt
skill_df[skill_df['Year_y'].dt.strftime('%Y')=='2019']

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
import datetime as dt
skill_df['Date']= pd.to_datetime
skill_df.loc[df.dt.year.eq(2019),'Tgt'].values.tolist()

In [32]:
# 2022 NFL RB Draft Order Data Frame 
main_df = df[['Player', 'Tm', 'Pos', 'Tgt', 'Rec', 'GS', 'ReceivingYds', 'RushingYds', 'RushingTD', 'RushingAtt', 'ReceivingTD', 'FantasyPoints', 'Year']]
main_df.head(10)

,Player,Tm,Pos,Tgt,Rec,GS,ReceivingYds,RushingYds,RushingTD,RushingAtt,ReceivingTD,FantasyPoints,Year
0,Christian McCaffrey,CAR,RB,142.0,116.0,16,1005.0,1387.0,15.0,287.0,4.0,469.20,NaN
1,Lamar Jackson,BAL,QB,0.0,0.0,15,0.0,1206.0,7.0,176.0,0.0,415.68,NaN
2,Derrick Henry,TEN,RB,24.0,18.0,15,206.0,1540.0,16.0,303.0,2.0,294.60,NaN
3,Aaron Jones,GNB,RB,68.0,49.0,16,474.0,1084.0,16.0,236.0,3.0,314.80,NaN
4,Ezekiel Elliott,DAL,RB,71.0,54.0,16,420.0,1357.0,12.0,301.0,2.0,311.70,NaN
5,Dalvin Cook,MIN,RB,63.0,53.0,14,519.0,1135.0,13.0,250.0,0.0,292.40,NaN
6,Michael Thomas,NOR,WR,185.0,149.0,15,1725.0,-9.0,0.0,1.0,9.0,374.60,NaN
7,Travis Kelce,KAN,TE,136.0,97.0,16,1229.0,4.0,1.0,1.0,5.0,254.30,NaN
8,Nick Chubb,CLE,RB,49.0,36.0,16,278.0,1494.0,8.0,298.0,0.0,255.20,NaN
9,Austin Ekeler,LAC,RB,108.0,92.0,8,993.0,557.0,3.0,132.0,8.0,309.00,NaN

In [33]:
# Changing column names from  G to Games (Played) and AVG to (ADP) Average Draft Position and viewing
main_df = main_df.rename(columns={'Tm':'Team', 'GS':'Games'})
main_df.head(10)

,Player,Team,Pos,Tgt,Rec,Games,ReceivingYds,RushingYds,RushingTD,RushingAtt,ReceivingTD,FantasyPoints,Year
0,Christian McCaffrey,CAR,RB,142.0,116.0,16,1005.0,1387.0,15.0,287.0,4.0,469.20,NaN
1,Lamar Jackson,BAL,QB,0.0,0.0,15,0.0,1206.0,7.0,176.0,0.0,415.68,NaN
2,Derrick Henry,TEN,RB,24.0,18.0,15,206.0,1540.0,16.0,303.0,2.0,294.60,NaN
3,Aaron Jones,GNB,RB,68.0,49.0,16,474.0,1084.0,16.0,236.0,3.0,314.80,NaN
4,Ezekiel Elliott,DAL,RB,71.0,54.0,16,420.0,1357.0,12.0,301.0,2.0,311.70,NaN
5,Dalvin Cook,MIN,RB,63.0,53.0,14,519.0,1135.0,13.0,250.0,0.0,292.40,NaN
6,Michael Thomas,NOR,WR,185.0,149.0,15,1725.0,-9.0,0.0,1.0,9.0,374.60,NaN
7,Travis Kelce,KAN,TE,136.0,97.0,16,1229.0,4.0,1.0,1.0,5.0,254.30,NaN
8,Nick Chubb,CLE,RB,49.0,36.0,16,278.0,1494.0,8.0,298.0,0.0,255.20,NaN
9,Austin Ekeler,LAC,RB,108.0,92.0,8,993.0,557.0,3.0,132.0,8.0,309.00,NaN

In [34]:
# Running Back Featured Columns with Usage Ranking and Total Yards From Scrimmage
skill_df = main_df.loc[df['Pos'] == 'RB', ['Player', 'Team', 'Pos','Tgt', 'Rec','RushingAtt', 'ReceivingYds','FantasyPoints', 'Games',]]
skill_df['Usage'] = ((df['Tgt'] + df['RushingAtt']) / main_df['Games'])
skill_df['Touchdowns'] = df['RushingTD'] + df['ReceivingTD']
skill_df['TotYdsScrm']= df['ReceivingYds']+ df['RushingYds']
skill_df.head(100)

,Player,Team,Pos,Tgt,Rec,RushingAtt,ReceivingYds,FantasyPoints,Games,Usage,Touchdowns,TotYdsScrm
0,Christian McCaffrey,CAR,RB,142.0,116.0,287.0,1005.0,469.20,16,26.812500,19.0,2392.0
2,Derrick Henry,TEN,RB,24.0,18.0,303.0,206.0,294.60,15,21.800000,18.0,1746.0
3,Aaron Jones,GNB,RB,68.0,49.0,236.0,474.0,314.80,16,19.000000,19.0,1558.0
4,Ezekiel Elliott,DAL,RB,71.0,54.0,301.0,420.0,311.70,16,23.250000,14.0,1777.0
5,Dalvin Cook,MIN,RB,63.0,53.0,250.0,519.0,292.40,14,22.357143,13.0,1654.0
...,...,...,...,...,...,...,...,...,...,...,...,...
352,T.J. Yeldon,BUF,RB,15.0,13.0,17.0,124.0,29.70,0,inf,0.0,187.0
353,Andrew Beck,DEN,RB,12.0,9.0,1.0,90.0,24.54,6,2.166667,1.0,93.0
359,Wendell Smallwood,WAS,RB,13.0,9.0,22.0,64.0,23.50,0,inf,0.0,145.0
362,Trey Edmunds,PIT,RB,7.0,6.0,22.0,48.0,20.00,0,inf,0.0,140.0
364,Wes Hills,DET,RB,2.0,2.0,10.0,1.0,16.20,1,12.000000,2.0,22.0